# Generated by Django 5.1.4 on 2024-12-13 19:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='ecard',
            name='issued_date',
        ),
        migrations.RemoveField(
            model_name='ecard',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='ecard',
            name='card_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecard',
            name='ecard_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ecard',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar', models.CharField(blank=True, max_length=12, null=True)),
                ('pan', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('bank_details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('In Process', 'In Process'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='In Process', max_length=20)),
                ('ecard_generated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
